#!/bin/bash

bash slurm_scripts/nextstep_stage1_skillonly.sh

bash slurm_scripts/nextstep_stage2_frzembB.sh
sbatch slurm_scripts/nextstep_stage3_frzembB_actiononly.sh

bash slurm_scripts/nextstep_stage2_onlyembA.sh
sbatch slurm_scripts/nextstep_stage3_onlyembA_actiononly.sh

bash slurm_scripts/nextstep_stage3_frzembB_actiononly.sh
bash slurm_scripts/nextstep_stage3_onlyembA_actiononly.sh
